- name: Deploy all analytics services to a single node
  hosts: all
  become: True
  gather_facts: True
  vars:
    migrate_db: "yes"
    disable_edx_services: false
    ENABLE_DATADOG: False
    ENABLE_NEWRELIC: False
  roles:
    - aws
    - mysql
    - memcache
    - role: edxlocal
      when: EDXAPP_MYSQL_HOST == 'localhost'
    - analytics_api
    - analytics_pipeline
    - role: nginx
      nginx_sites:
        - insights
    - insights
