- hosts: all
  become: True
  vars:
    # By default take instances in and out of the elb(s) they
    # are attached to
    # To skip elb operations use "-e elb_pre_post=fase"
    elb_pre_post: true
    # Number of instances to operate on at a time
    serial_count: 1
    CLUSTER_NAME: "commoncluster"
  serial: "{{ serial_count }}"
  roles:
    - common
    - aws
    - elasticsearch
