---
- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Configure instance(s)
  hosts: all
  become: True
  gather_facts: True
  vars:
<<<<<<< HEAD
    COMMON_ENABLE_DATADOG: False
    COMMON_ENABLE_SPLUNKFORWARDER: True
    COMMON_ENABLE_NEWRELIC: True
=======
    COMMON_ENABLE_DATADOG: True
    COMMON_ENABLE_SPLUNKFORWARDER: True
>>>>>>> Proversity/development (#85)
    COMMON_SECURITY_UPDATES: yes
    SECURITY_UPGRADE_ON_ANSIBLE: true

    SPLUNKFORWARDER_LOG_ITEMS:
<<<<<<< HEAD
      - source: '/var/lib/jenkins/jobs/edx-platform-*/builds/*/junitResult.xml'
=======
      - source: '/var/lib/jenkins/jobs/*/builds/*/junitResult.xml'
>>>>>>> Proversity/development (#85)
        recursive: true
        index: 'testeng'
        sourcetype: junit
        followSymlink: false
<<<<<<< HEAD
        blacklist: coverage|private|subset|specific|custom|special|\.gz$
=======
        blacklist: '\.gz$'
>>>>>>> Proversity/development (#85)
        crcSalt: '<SOURCE>'

      - source: '/var/lib/jenkins/jobs/*/builds/*/build.xml'
        index: 'testeng'
        recursive: true
        sourcetype: build_result
        followSymlink: false
        crcSalt: '<SOURCE>'
        blacklist: '\.gz$'

<<<<<<< HEAD
      - source: '/var/lib/jenkins/jobs/edx-platform-*/builds/*/archive/.../test_root/log/timing.*.log'
        index: 'testeng'
        recursive: true
        sourcetype: 'json_timing_log'
        followSymlink: false
        crcSalt: '<SOURCE>'
        blacklist: coverage|private|subset|specific|custom|special|\.gz$

=======
>>>>>>> Proversity/development (#85)
      - source: '/var/lib/jenkins/jobs/edx-platform-*/builds/*/archive/test_root/log/timing.*.log'
        index: 'testeng'
        recursive: true
        sourcetype: 'json_timing_log'
        followSymlink: false
        crcSalt: '<SOURCE>'
        blacklist: coverage|private|subset|specific|custom|special|\.gz$

      - source: '/var/log/jenkins/jenkins.log'
        index: 'testeng'
        recursive: false
        followSymlink: false
        blacklist: '\.gz$'

  roles:
    - aws
    - role: datadog
      when: COMMON_ENABLE_DATADOG

    - jenkins_build

    # run just the splunkforwarder role by using '--tags "splunkonly"'
    # e.g. ansible-playbook jenkins_testeng_master.yml -i inventory.ini --tags "splunkonly" -vvvv
    - role: splunkforwarder
      when: COMMON_ENABLE_SPLUNKFORWARDER
      tags:
        - splunkonly
        - jenkins:promote-to-production
      become: True
<<<<<<< HEAD

    - role: newrelic
      when: COMMON_ENABLE_NEWRELIC
      tags:
        - newreliconly
=======
>>>>>>> Proversity/development (#85)
