---
<<<<<<< HEAD
=======
#
# edX Configuration
#
# github:     https://github.com/edx/configuration
# wiki:       https://openedx.atlassian.net/wiki/display/OpenOPS
# code style: https://openedx.atlassian.net/wiki/display/OpenOPS/Ansible+Code+Conventions
# license:    https://github.com/edx/configuration/blob/master/LICENSE.TXT
#
#
#
# Tasks for role ecommerce
#
# Overview:
#
#
# Dependencies:
#
#
# Example play:
#
#
- name: Add gunicorn configuration file
  template:
    src: "edx/app/ecommerce/ecommerce_gunicorn.py.j2"
    dest: "{{ ecommerce_home }}/ecommerce_gunicorn.py"
  become_user: "{{ ecommerce_user }}"
  tags:
      - install
      - install:configuration

- name: Install application requirements
  pip:
    requirements: "{{ ecommerce_requirements_base }}/{{ item }}"
    virtualenv: "{{ ecommerce_venv_dir }}"
    state: present
  become_user: "{{ ecommerce_user }}"
  with_items: "{{ ecommerce_requirements }}"
  tags:
    - install
    - install:app-requirements

- name: Create nodeenv
  shell: "{{ ecommerce_venv_dir }}/bin/nodeenv {{ ecommerce_nodeenv_dir }} --node={{ ecommerce_node_version }} --prebuilt --force"
  become_user: "{{ ecommerce_user }}"
  tags:
    - install
    - install:system-requirements

- name: Install node dependencies
  npm:
    executable: "{{ ecommerce_nodeenv_bin }}/npm"
    path: "{{ ecommerce_code_dir }}"
    production: yes
    state: latest
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  tags:
    - install
    - install:app-requirements

- name: Install bower dependencies
  shell: ". {{ ecommerce_nodeenv_bin }}/activate && {{ ecommerce_node_bin }}/bower install --production --config.interactive=false"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  tags:
    - install
    - install:app-requirements

# This is a hacked fix for the fact that the table `thumbnail_kvstore` exists in
# some environments, which won't need the 3rd party newly introduced migration
# to create this table, so we fake the migration.
# This is required for the Ginkgo release.
# TODO: Delete this task for the Hawthorn release.
- name: fake thumbnails
  shell: >
    table_exists=`mysql -uroot -ss -e "SELECT EXISTS(SELECT * FROM information_schema.tables WHERE table_schema = '{{ ECOMMERCE_DEFAULT_DB_NAME }}' AND table_name = 'thumbnail_kvstore')"`;
    if [ "$table_exists" -eq "1" ]; then {{ ecommerce_venv_dir }}/bin/python ./manage.py migrate thumbnail 0001 --fake; fi;
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db

- name: Migrate
  shell: >
    DB_MIGRATION_USER='{{ COMMON_MYSQL_MIGRATE_USER }}'
    DB_MIGRATION_PASS='{{ COMMON_MYSQL_MIGRATE_PASS }}'
    {{ ecommerce_venv_dir }}/bin/python ./manage.py migrate --noinput
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db

- name: Populate countries
  shell: "DB_MIGRATION_USER={{ COMMON_MYSQL_MIGRATE_USER }} DB_MIGRATION_PASS={{ COMMON_MYSQL_MIGRATE_PASS }} {{ ecommerce_venv_dir }}/bin/python ./manage.py oscar_populate_countries --initial-only"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  when: migrate_db is defined and migrate_db|lower == "yes"
  tags:
    - migrate
    - migrate:db

- name: compile sass
  shell: "{{ ecommerce_venv_dir }}/bin/python manage.py {{ item }}"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  with_items:
    - "update_assets --skip-collect"
  when: not devstack
  tags:
    - assets
    - assets:gather

- name: Run r.js optimizer
  shell: ". {{ ecommerce_nodeenv_bin }}/activate && {{ ecommerce_node_bin }}/r.js -o build.js"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  when: not devstack
  tags:
    - assets
    - assets:gather

- name: Run collectstatic
  shell: "{{ ecommerce_venv_dir }}/bin/python manage.py {{ item }}"
  args:
    chdir: "{{ ecommerce_code_dir }}"
  become_user: "{{ ecommerce_user }}"
  environment: "{{ ecommerce_environment }}"
  with_items:
    - "collectstatic --noinput"
    - "compress"
  when: not devstack
  tags:
    - assets
    - assets:gather

- name: Write out the supervisor wrapper
  template:
    src: "edx/app/ecommerce/ecommerce.sh.j2"
    dest: "{{ ecommerce_home }}/{{ ecommerce_service_name }}.sh"
    mode: "0650"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: Write supervisord config
  template:
    src: "edx/app/supervisor/conf.d.available/ecommerce.conf.j2"
    dest: "{{ supervisor_available_dir }}/{{ ecommerce_service_name }}.conf"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  tags:
    - install
    - install:configuration

>>>>>>> force flag for compress
- name: Create Apple Pay certificates directory
  file:
    path: "{{ ecommerce_apple_pay_merchant_certificate_directory }}"
    state: directory
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
  tags:
    - install
    - install:configuration

- name: Write Apple Pay merchant certificates
  copy:
    content: "{{ ECOMMERCE_APPLE_PAY_MERCHANT_CERTIFICATE }}"
    dest: "{{ ecommerce_apple_pay_merchant_certificate_path }}"
    owner: "{{ supervisor_user }}"
    group: "{{ common_web_user }}"
    mode: "0644"
  no_log: true
  tags:
    - install
    - install:configuration
