- name: Create openvpn config file
  template:
    src: server.conf.j2
    dest: "{{ openvpn_base_dir }}/{{openvpn_config_file}}.conf"
    owner: root
    group: root
  notify:
    - restart openvpn

- name: Install LDAP config
  template:
    src: ldap.conf.j2
    dest: "{{ openvpn_base_dir }}/auth/ldap.conf"
    owner: root
    group: root
  when: openvpn_use_ldap

- name: Copy openvpn logrotate config file
  copy:
    src: openvpn_logrotate.conf
    dest: /etc/logrotate.d/openvpn.conf
    owner: root
    group: root
    mode: 0400
  when: ansible_os_family != 'Solaris'

- name: Ensure ccd directory exists
  file:
    path: "{{ openvpn_base_dir }}/{{ ccd_dir_name }}"
    state: directory
  when: openvpn_use_ccd

- name: Create ccd config files
  template:
    src: ccd_client.j2
    dest: "{{ openvpn_base_dir }}/{{ ccd_dir_name }}/OpenVPN-Client-{{ inventory_hostname[:24] }}-{{ item.name[:24] }}"
  with_items: "{{ ccd_clients }}"
  when: openvpn_use_ccd

- name: Setup openvpn auto-start & start
  service:
    name: "{{openvpn_service_name}}"
    enabled: yes
    state: started
