- name: Change facts to use netfilter-persistent on Debian >= 9 or Ubuntu >= 16
  set_fact:
    iptables_save_command: "/usr/sbin/netfilter-persistent save"
    iptables_service: netfilter-persistent
  when: (ansible_distribution == 'Debian' and ansible_lsb.major_release|int >= 9) or (ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int >= 16)

- name: Install iptables-persistent (Debian/Ubuntu)
  package:
    name: iptables-persistent
    state: present
  when: ansible_os_family == "Debian"

- name: Enable iptables
  service:
    name: "{{ iptables_service }}"
    enabled: true
    state: started

- name: iptables - Allow VPN forwarding
  iptables:
    chain: FORWARD
    source: "{{ item.source }}"
    destination: "{{ item.destination }}"
    jump: "{{ item.jump }}"
    comment: "Allow VPN forwarding"
  with_items: "{{ openvpn_forwarding_iptables_rules }}"
  notify: "save iptables"

- name: iptables - Allow incoming VPN connection
  iptables:
    chain: INPUT
    protocol: "{{openvpn_proto}}"
    destination_port: "{{openvpn_port}}"
    jump: ACCEPT
    comment: "Allow incoming VPN connection"
  notify: "save iptables"

- name: iptables - Accept packets from VPN tunnel adaptor
  iptables:
    chain: INPUT
    in_interface: tun0
    jump: ACCEPT
    comment: "Accept packets from VPN tunnel adaptor"
  notify: "save iptables"

- name: iptables - Perform NAT readdressing
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ item.source }}"
    to_source: "{{ansible_default_ipv4.address}}"
    jump: SNAT
    comment: "Perform NAT readdressing"
  with_items: "{{ openvpn_forwarding_iptables_rules }}"

  when: not openvpn_masquerade_not_snat

- name: iptables - Perform NAT readdressing with MASQUERADE
  iptables:
    table: nat
    chain: POSTROUTING
    source: "{{ item.source }}"
    jump: MASQUERADE
    comment: "Perform NAT readdressing"
  with_items: "{{ openvpn_forwarding_iptables_rules }}"
  when: openvpn_masquerade_not_snat
  notify: "save iptables"
