---

- name: Check hosts
  hosts: all
  gather_facts: no
  tasks:
    - set_fact:
        hosts_confirmed: true
      delegate_to: localhost
      delegate_facts: true

- name: Verify hosts
  hosts: localhost
  gather_facts: no
  tasks:
    - assert:
        that: hosts_confirmed | default(false)

- name: Making backups in persistence servers
  become: True
  hosts: all
  gather_facts: True
  roles:
    - role: mongo_backup  # ednx role
      tags:
        - mongo_backup
