---
# Installation of exporters and Prometheus data gatherer

- name: Bootstrap instances
  hosts: all
  gather_facts: no
  become: true
  roles:
    - python

- hosts: monitored_servers
  become: True
  roles:
    - cloudalchemy.node-exporter
  tags: install:nodes

- hosts: monitoring_servers
  become: True
  roles:
  - cloudalchemy.prometheus
  tags: install:prometheus
