---
# Persistence services deploy: Memcache, RabbitMQ and Elasticsearch

- name: Bootstrap instance(s)
  hosts: all
  gather_facts: no
  become: True
  roles:
    - python

- name: Deploy persistence services and workers backend
  hosts: all
  become: True
  gather_facts: True
  roles:
    - role: memcache
    - role: rabbitmq
      rabbitmq_ip: 0.0.0.0
    - role: elasticsearch
