---

MONGO_BACKUP_ROOT: "/var/edunext_tmp"
MONGO_BACKUP_DATE: "{{ ansible_date_time.date }}"
MONGO_BACKUP_LOCATION: "{{ MONGO_BACKUP_ROOT }}/{{ MONGO_BACKUP_DATE }}.d"
mongo_artifact_path: "{{ MONGO_BACKUP_ROOT }}"
MONGO_BACKUP_PRE_CLEAN_ROOT: false

# Mongo backup storage options

MONGO_BACKUP_STORAGE_OPTIONS:
  EXTERNAL_STORAGE_TYPE: "aws"
  EXTERNAL_STORAGE_OPTIONS:
    S3_BUCKET_NAME: "SET ME PLEASE"
    AWS_ACCESS_KEY_ID: "SET ME PLEASE"
    AWS_SECRET_ACCESS_KEY: "SET ME PLEASE"
